// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHpsuaKHUvBZWbhJUbY53ErBWoUGVgX0k',
    appId: '1:990716361936:android:74f102c45eb2fa6852b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
    databaseURL: "https://flutter-projects-94ac5-default-rtdb.asia-southeast1.firebasedatabase.app/"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbACa3E_kYCIO0OS66c9r7LdOcGJDPflU',
    appId: '1:990716361936:ios:b3dcc2b188611a1452b2d5',
    messagingSenderId: '990716361936',
    projectId: 'flutter-projects-94ac5',
    storageBucket: 'flutter-projects-94ac5.appspot.com',
    iosBundleId: 'com.example.testingRealtimeDatabaseFlutter',
  );
}
